image: Ubuntu

stack: python 3

install:
- echo "Downloading conan..."
#- set PATH=%PATH%;%PYTHON%/Scripts/
- pip.exe install conan
- conan user # Create the conan data directory
- conan --version

build_script:
- mkdir build
- conan install .
- cd build
- cmake ..
- make
